const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const data={settings:{theme:'#bc4b19',business:{name:'Auto-école Walid Nafougui'}},driving_config:{open_time:'08:00',close_time:'18:00',default_lesson_minutes:60},students:[{id:1,name:'Amine Ben Mohamed',phone:'22123456',cin:'12345678',permit:'B',status:'Actif',package:1200,driving_target:20,document_status:'Incomplet'}],instructors:[{id:1,name:'Walid Nafougui',status:'Actif',phone:'22123456',permit:'B'}],vehicles:[{id:1,brand:'Renault',model:'Clio',plate:'123 TU 4567',status:'Disponible',mileage:42000,insurance_expiry:'2027-01-01',visit_expiry:'2027-02-01'}],lessons:[{id:1,student_id:1,instructor_id:1,vehicle_id:1,start:'2026-09-12T10:00',duration:60,kind:'Conduite',status:'Planifiée'}],exams:[{id:1,student_id:1,type:'Conduite',date:'2026-09-20',result:'Prévu',center:'Tunis'}],driving_payments:[{id:1,student_id:1,time:'2026-09-12T09:00',amount:250,method:'Espèces'}],expenses:[],driving_documents:[],driving_packages:[],package_sales:[],vehicle_events:[],instructor_absences:[],driving_audits:[],driving_invoices:[]};
const server=http.createServer((req,res)=>{const name=req.url==='/'?'index.html':req.url.slice(1).split('?')[0];const file=path.join(__dirname,'web',name);if(fs.existsSync(file)&&fs.statSync(file).isFile()){res.setHeader('Content-Type',name.endsWith('.css')?'text/css':name.endsWith('.js')?'application/javascript':name.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(file));}else{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:'C:/Users/user/AppData/Local/ms-playwright/chromium-1228/chrome-win64/chrome.exe'});const page=await browser.newPage();console.log('Browser ready');const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('JS:',e.message)});
await page.route('**/api/**',async route=>{const url=route.request().url();if(url.includes('/branding/logo'))return route.fulfill({contentType:'image/png',body:fs.readFileSync(path.join(__dirname,'assets/logo.png'))});let result=url.includes('/license/status')?{activated:true}:url.includes('/auth/status')?{authenticated:true,configured:true,username:'walid',role:'Administrateur'}:url.includes('/public/branding')?{business:data.settings.business,theme:'#bc4b19'}:url.includes('/driving/users')?[]:data;await route.fulfill({json:{ok:true,data:result}});});
console.log('Loading');await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded',timeout:15000});console.log('Loaded');await page.waitForSelector('#studentsGrid .studentcard',{timeout:15000,state:'attached'});
await page.locator('#nav [data-page=students]').click();const firstCandidate=page.locator('#studentsGrid .studentcard').first();await firstCandidate.locator('.pilot-more summary').click();const candidateBox=await firstCandidate.boundingBox(),candidateMenuBox=await firstCandidate.locator('.pilot-menu').boundingBox();assert(candidateMenuBox.y>=candidateBox.y&&candidateMenuBox.y+candidateMenuBox.height<=candidateBox.y+candidateBox.height,'candidate menu is not positioned over its own card');await firstCandidate.locator('.pilot-more summary').click();
fs.mkdirSync(path.join(__dirname,'output/ui'),{recursive:true});
for(const [width,height] of [[1366,768],[1536,864],[1920,1080]]){await page.setViewportSize({width,height});for(const module of ['dashboard','students','schedule','alertsPage','exams','finance','fleet','operations','reports','settings']){await page.locator('#nav [data-page="'+module+'"]').click();await page.waitForTimeout(30);assert(await page.locator('#'+module).isVisible(),module+' hidden');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),module+' page overflow');}
await page.locator('#nav [data-page=dashboard]').click();await page.screenshot({path:path.join(__dirname,'output/ui/dashboard-'+width+'.png')});}
await page.setViewportSize({width:1366,height:768});
for(const type of ['student','lesson','exam','payment','invoice','expense','vehicle','instructor','package','package_sale','document','vehicle_event','absence']){await page.evaluate(t=>openForm(t),type);assert(await page.locator('#modal').isVisible(),type);assert(await page.locator('#cancelModal').isVisible(),type+' actions');await page.locator('#cancelModal').click();}
await page.locator('#nav [data-page=schedule]').click();await page.locator('#weekNext').click();await page.locator('[data-planning-view=month]').click();await page.locator('#weekGrid [data-day]').last().click();await page.screenshot({path:path.join(__dirname,'output/ui/planning.png')});
await page.evaluate(()=>openProfile(1));await page.screenshot({path:path.join(__dirname,'output/ui/profile.png')});await page.locator('#profileClose').click();
await page.locator('#nav [data-page=settings]').click();for(const tab of await page.locator('.settings-tab').all()){await tab.click();}await page.locator('.settings-tab').first().click();await page.screenshot({path:path.join(__dirname,'output/ui/settings.png')});
await page.evaluate(()=>{document.querySelector('#app').classList.add('hidden');document.querySelector('#authScreen').classList.remove('hidden');});await page.screenshot({path:path.join(__dirname,'output/ui/login.png')});
await page.evaluate(()=>showApp('walid'));await page.waitForFunction(()=>!document.querySelector('#app').classList.contains('hidden'));assert(await page.locator('#authScreen').evaluate(el=>el.classList.contains('hidden')&&getComputedStyle(el).display==='none'),'login screen remained above dashboard');assert((await page.locator('#app').boundingBox()).y<5,'dashboard did not return to top after login');
assert.deepEqual(errors,[]);console.log('PASS: 10 modules, 3 desktop sizes, 13 forms, profile, planning controls, settings, login transition; no JS errors or page overflow.');await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});
